### ISSUE TITLE
cellcycle.calc_cellcycle_ordering

### ISSUE THREAD

**Issue by zcq23** [skelviper/HiRES#3]
Hi Zhiyuan, I try to follow the script "1_calc_pairs_features.ipynb" for cellcycling, but met the error like this:
>>> ordering = cellcycle.calc_cellcycle_ordering(metadata,threads=60)
/./cellcycle/CHARMtools/mdso/spectral_ordering_.py:319: UserWarning: new similarity disconnected. Reordering connected components.
  warnings.warn(warning_msg)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/./cellcycle/CHARMtools/cellcycle.py", line 133, in calc_cellcycle_ordering
    order = _mdso(cdps,filesp,n_components)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/./cellcycle/CHARMtools/cellcycle.py", line 106, in _mdso
    return list(annote.iloc[so_res].index)
                ~~~~~~~~~~~^^^^^^^^
  File "/./.conda/envs/cellcycle/lib/python3.12/site-packages/pandas/core/indexing.py", line 1191, in __getitem__
    return self._getitem_axis(maybe_callable, axis=axis)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/./.conda/envs/cellcycle/lib/python3.12/site-packages/pandas/core/indexing.py", line 1743, in _getitem_axis       
    return self._get_list_axis(key, axis=axis)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/./.conda/envs/cellcycle/lib/python3.12/site-packages/pandas/core/indexing.py", line 1714, in _get_list_axis      
    return self.obj._take_with_is_copy(key, axis=axis)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/./.conda/envs/cellcycle/lib/python3.12/site-packages/pandas/core/generic.py", line 4153, in _take_with_is_copy   
    result = self.take(indices=indices, axis=axis)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/./.conda/envs/cellcycle/lib/python3.12/site-packages/pandas/core/generic.py", line 4133, in take
    new_data = self._mgr.take(
               ^^^^^^^^^^^^^^^
  File "/./.conda/envs/cellcycle/lib/python3.12/site-packages/pandas/core/internals/managers.py", line 894, in take       
    return self.reindex_indexer(
           ^^^^^^^^^^^^^^^^^^^^^
  File "/./.conda/envs/cellcycle/lib/python3.12/site-packages/pandas/core/internals/managers.py", line 688, in reindex_indexer
    blk.take_nd(
  File "/./.conda/envs/cellcycle/lib/python3.12/site-packages/pandas/core/internals/blocks.py", line 1307, in take_nd     
    new_values = algos.take_nd(
                 ^^^^^^^^^^^^^^
  File "/./.conda/envs/cellcycle/lib/python3.12/site-packages/pandas/core/array_algos/take.py", line 117, in take_nd      
    return _take_nd_ndarray(arr, indexer, axis, fill_value, allow_fill)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/./.conda/envs/cellcycle/lib/python3.12/site-packages/pandas/core/array_algos/take.py", line 162, in _take_nd_ndarray
    func(arr, indexer, out, fill_value)
  File "pandas/_libs/algos_take_helper.pxi", line 2096, in pandas._libs.algos.take_2d_axis0_object_object
ValueError: Buffer has wrong number of dimensions (expected 1, got 2)

my CHARMtools is the downloaded folder "CHARMtools_snapshot" and then exported to PYTHONPATH, my metadata only has 9 cells and their .pairs.gz, so I expanded them by simply copying and named after _1, _2, _3... for each cell, because I just want to calculate their cellcycling scores and not entirely include the K-means for clustering in this test time.
>>> metadata
            Cellname                                              pairs
0    SRR1-15-2_raw_1  /./cellcycle/expanded_files/SRR1...
1    SRR1-15-2_raw_2  /./cellcycle/expanded_files/SRR1...
2    SRR1-15-2_raw_3  /./cellcycle/expanded_files/SRR1...
3    SRR1-15-2_raw_4  /./cellcycle/expanded_files/SRR1...
4    SRR1-15-2_raw_5  /./cellcycle/expanded_files/SRR1...
..               ...                                                ...
175   SRR21505180_16  /./cellcycle/expanded_files/SRR2...
176   SRR21505180_17  /./cellcycle/expanded_files/SRR2...
177   SRR21505180_18  /./cellcycle/expanded_files/SRR2...
178   SRR21505180_19  /./cellcycle/expanded_files/SRR2...
179   SRR21505180_20  /./cellcycle/expanded_files/SRR2...

[180 rows x 2 columns]
I don't know where can do to adjust this problem😭veryyyyyyyyyyyyyyyyyy hope for your reply and thanks in advance!!!

**Comment by zcq23** [comment]
> Hi Zhiyuan, I try to follow the script "1_calc_pairs_features.ipynb" for cellcycling, but met the error like this:
> 
> > > > ordering = cellcycle.calc_cellcycle_ordering(metadata,threads=60)
> > > > /./cellcycle/CHARMtools/mdso/spectral_ordering_.py:319: UserWarning: new similarity disconnected. Reordering connected components.
> > > > warnings.warn(warning_msg)
> > > > Traceback (most recent call last):
> > > > File "", line 1, in 
> > > > File "/./cellcycle/CHARMtools/cellcycle.py", line 133, in calc_cellcycle_ordering
> > > > order = _mdso(cdps,filesp,n_components)
> > > > ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> > > > File "/./cellcycle/CHARMtools/cellcycle.py", line 106, in _mdso
> > > > return list(annote.iloc[so_res].index)
> > > > ~~~~~~~~~~~^^^^^^^^
> > > > File "/./.conda/envs/cellcycle/lib/python3.12/site-packages/pandas/core/indexing.py", line 1191, in **getitem**
> > > > return self._getitem_axis(maybe_callable, axis=axis)
> > > > ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> > > > File "/./.conda/envs/cellcycle/lib/python3.12/site-packages/pandas/core/indexing.py", line 1743, in _getitem_axis
> > > > return self._get_list_axis(key, axis=axis)
> > > > ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> > > > File "/./.conda/envs/cellcycle/lib/python3.12/site-packages/pandas/core/indexing.py", line 1714, in _get_list_axis
> > > > return self.obj._take_with_is_copy(key, axis=axis)
> > > > ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> > > > File "/./.conda/envs/cellcycle/lib/python3.12/site-packages/pandas/core/generic.py", line 4153, in _take_with_is_copy
> > > > result = self.take(indices=indices, axis=axis)
> > > > ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> > > > File "/./.conda/envs/cellcycle/lib/python3.12/site-packages/pandas/core/generic.py", line 4133, in take
> > > > new_data = self._mgr.take(
> > > > ^^^^^^^^^^^^^^^
> > > > File "/./.conda/envs/cellcycle/lib/python3.12/site-packages/pandas/core/internals/managers.py", line 894, in take
> > > > return self.reindex_indexer(
> > > > ^^^^^^^^^^^^^^^^^^^^^
> > > > File "/./.conda/envs/cellcycle/lib/python3.12/site-packages/pandas/core/internals/managers.py", line 688, in reindex_indexer
> > > > blk.take_nd(
> > > > File "/./.conda/envs/cellcycle/lib/python3.12/site-packages/pandas/core/internals/blocks.py", line 1307, in take_nd
> > > > new_values = algos.take_nd(
> > > > ^^^^^^^^^^^^^^
> > > > File "/./.conda/envs/cellcycle/lib/python3.12/site-packages/pandas/core/array_algos/take.py", line 117, in take_nd
> > > > return _take_nd_ndarray(arr, indexer, axis, fill_value, allow_fill)
> > > > ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> > > > File "/./.conda/envs/cellcycle/lib/python3.12/site-packages/pandas/core/array_algos/take.py", line 162, in _take_nd_ndarray
> > > > func(arr, indexer, out, fill_value)
> > > > File "pandas/_libs/algos_take_helper.pxi", line 2096, in pandas._libs.algos.take_2d_axis0_object_object
> > > > ValueError: Buffer has wrong number of dimensions (expected 1, got 2)
> 
> my CHARMtools is the downloaded folder "CHARMtools_snapshot" and then exported to PYTHONPATH, my metadata only has 9 cells and their .pairs.gz, so I expanded them by simply copying and named after _1, _2, _3... for each cell, because I just want to calculate their cellcycling scores and not entirely include the K-means for clustering in this test time.
> 
> > > > metadata
> > > > Cellname                                              pairs
> > > > 0    SRR1-15-2_raw_1  /./cellcycle/expanded_files/SRR1...
> > > > 1    SRR1-15-2_raw_2  /./cellcycle/expanded_files/SRR1...
> > > > 2    SRR1-15-2_raw_3  /./cellcycle/expanded_files/SRR1...
> > > > 3    SRR1-15-2_raw_4  /./cellcycle/expanded_files/SRR1...
> > > > 4    SRR1-15-2_raw_5  /./cellcycle/expanded_files/SRR1...
> > > > ..               ...                                                ...
> > > > 175   SRR21505180_16  /./cellcycle/expanded_files/SRR2...
> > > > 176   SRR21505180_17  /./cellcycle/expanded_files/SRR2...
> > > > 177   SRR21505180_18  /./cellcycle/expanded_files/SRR2...
> > > > 178   SRR21505180_19  /./cellcycle/expanded_files/SRR2...
> > > > 179   SRR21505180_20  /./cellcycle/expanded_files/SRR2...
> 
> [180 rows x 2 columns] I don't know where can do to adjust this problem😭veryyyyyyyyyyyyyyyyyy hope for your reply and thanks in advance!!!

oh I found that imputing the *.pairs.gz to mix offered by the article in GEO will fix the problem, thanks a lot indeed !!!!!!!!!!!!!!!!!!!
